spring.application.name=weather
server.port=8090

# OpenStreetMap Base Url
api.nominatim.url=https://nominatim.openstreetmap.org

# NWS Base Url
api.nws.url=https://api.weather.gov

# App Identification
app.user-agent=SpringAI-MCP-WeatherApp/1.0 (testmcpserver@gmail.com)
